### ISSUE TITLE
railway deploy not working anymore .

### ISSUE THREAD

**Issue by AkumaX1** [TheCaduceus/WARP-UNLIMITED-ADVANCED#23]
filestream dependency banned.

**Comment by TheCaduceus** [comment]
@AkumaX1 `filestream`? It does not involve it; this script is a simply Cron-Job. Better if you host it on your own device :) Because these small platforms which will die soon, I don't know in what sense it was blocked... I can simply say don't waste your time contacting them because they already shown their intelligence by doing this. 🤣

**Comment by umair786155** [comment]
Yeah, same issue. Fine on heroku and termux for me

**Comment by TheCaduceus** [comment]
@ravindusha Can you try it now?

**Comment by TheCaduceus** [comment]
@AkumaX1 Can you try the new template for railway? click the deployment button.
