### ISSUE TITLE
I'd like to ask

### ISSUE THREAD

**Issue by vjrmy** [TheCaduceus/WARP-UNLIMITED-ADVANCED#5]
is this safe? I won't get banned right? because I used the railyway app and I forgot to turn it off until almost 3000 referrals came to my place
![Screenshot_20220524-224416_1111](https://user-images.githubusercontent.com/88963059/170078106-8748d055-c0a7-4dea-b58c-23f34cbce75d.jpg)

**Comment by TheCaduceus** [comment]
I already answered this question in FAQ:

**5.Deploying this on Heroku/Railway/Okteto cause any ban?**
No, this script comes in category of Cron-Job because this script just takes the WARP/WARP+ ID from user and arrange it in a particular format and start pining it in an interval of 10 seconds. This script is lightweight and don't have any load on system.

**You can even continuously generate PBs of data non-stop.**
